name: societyapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_native_splash: ^0.1.9
  intro_slider: ^2.2.9
  shared_preferences: ^0.5.7
  flutter_screenutil: ^0.4.2
  http: ^0.12.0+4
  native_http: ^1.0.0+5
  toast: ^0.1.5
  carousel_slider: ^2.0.0
  transparent_image: ^1.0.0
  responsive_grid: ^1.1.1
  flutter_phone_direct_caller: ^1.0.1
  razorpay_flutter: ^1.1.4
  font_awesome_flutter: ^8.8.1
  awesome_button: ^1.0.2
  flutter_mailer: ^0.4.3
  esys_flutter_share: ^1.0.2
  flutter_form_bloc: ^0.13.0
  flutter_gradients: ^1.0.0+1
  flutter_syntax_view: ^1.0.0
  flash: ^1.2.0
  url_launcher: ^5.4.5
  flutter_markdown: ^0.3.4
  simple_animations: ^1.3.9
  auto_size_text: ^2.1.0
  flutter_fadein: ^1.1.1
  liquid_progress_indicator: ^0.3.2
  rxdart: ^0.23.1
  image_picker: ^0.6.6+1
  nice_button: ^0.1.7
  bot_toast: ^3.0.0
  flutter_html: ^0.11.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/

fonts:
  - family: CustomIcons
    fonts:
      - asset: assets/CustomIcons.ttf

  - family: Poppins-Bold
    fonts:
      - asset: assets/Poppins-Bold.ttf

  - family: Poppins-Medium
    fonts:
      - asset: assets/Poppins-Medium.ttf

  - family: JosefinSans
    fonts:
      - asset: assets/fonts/JosefinSans-Regular.ttf
      - asset: assets/fonts/JosefinSans-Bold.ttf
        weight: 700